# permissions for end users to view configmapcounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmapcount-viewer-role
rules:
- apiGroups:
  - silly.example.org
  resources:
  - configmapcounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - silly.example.org
  resources:
  - configmapcounts/status
  verbs:
  - get
